name: bronze-qiskit
channels:
  - defaults
dependencies:
  - pip>=25.3
  - python=3.12
  - matplotlib
  - pylatexenc 
  - pip:
      - qiskit==2.2.3
      - qiskit-aer==0.17.2
      - qiskit-ibm-runtime==0.43.1
